numpy la thư viện kiểu list 
vì numpy nhanh
có nhiều hàm tích hợp deer sử dụng cho AI
để sử dụng numpy thì pip install numpy 

In [1]:
import numpy as np

In [2]:
python_list = [1,2,3]
#chuyen đổi ds trene thành numpy list
numpy_list = np.array(python_list)
type(numpy_list)

numpy.ndarray

In [3]:
#list trong python có thể hổ trợ nhiều loại dữ liệu trong list
my_list = [1,'Chào',True, 2.0]

In [5]:
my_list = [1,2,3,4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [6]:
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [7]:
x = np.array([1,2,3,4,5,6,7,8]) # x = np.array(range(1,9))

In [8]:
#lấy số 4
x[3]

np.int64(4)

In [9]:
x[0:3]

array([1, 2, 3])

In [11]:
x[[2,4]]

array([3, 5])

In [26]:
data = [[1,2],[3,4],[5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [45]:
np_list[0::2,0]

array([1, 5])

In [ ]:
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]
np_list1 = np.array(x)
np_list1


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [52]:
#lấy số 2,6,10,14
np_list1[:,1]

array([ 2,  6, 10, 14])

In [ ]:
#lấy 7 và 11

In [53]:
np_list1[[1,2],2]

array([ 7, 11])

In [55]:
#lấy 4,7,10
np_list1[[0,1,2],[3,2,1]]

array([ 4,  7, 10])

In [56]:
np_list1[[3],[3,2,1,0]]

array([16, 15, 14, 13])

BTVN 01
cho matran = [[99,99,99],
              [99,99,99],
              [99,99,99]]
hãy tưởng tượng ô 99 trống
giả xử 1 là x
giả xử 0 lad o
lấy đầu vò từ phía x và phí o luân phiên
nếu đầu vào từ phía x là (0,0)
na trận sẽ trở thành
[[x,99,99],
 [99,99,99],
 [99,99,99]]

nếu đầu vào từ phía o là (0,0)
thông báo họ nhập lại
nếu không thì điền vào ma trận
Thử thách: nếu người đầu tiên có 3 phần tử liên tiếp thì dừng trò chơi

In [9]:
# Khởi tạo ma trận 3x3 toàn 99
matrix = [[99, 99, 99],
          [99, 99, 99],
          [99, 99, 99]]

current_player = 1  # X = 1, O = 0

# Hàm in ma trận
def print_matrix(m):
    for row in m:
        print(row)
    print()

# Hàm kiểm tra X thắng (3 số 1 liên tiếp)
def check_win(m):
    # Kiểm tra hàng
    for row in m:
        if row == [1, 1, 1]:
            return True

    # Kiểm tra cột
    for col in range(3):
        if m[0][col] == m[1][col] == m[2][col] == 1:
            return True

    # Kiểm tra đường chéo
    if m[0][0] == m[1][1] == m[2][2] == 1:
        return True
    if m[0][2] == m[1][1] == m[2][0] == 1:
        return True

    return False

# Vòng lặp trò chơi
while True:
    print_matrix(matrix)

    row = int(input("Nhập dòng (0-2): "))
    col = int(input("Nhập cột (0-2): "))

    # Kiểm tra ô đã nhập chưa
    if matrix[row][col] != 99:
        print("Ô đã được nhập, vui lòng nhập lại!")
        continue

    # Điền giá trị
    matrix[row][col] = current_player

    # Kiểm tra thắng
    if current_player == 1 and check_win(matrix):
        print_matrix(matrix)
        print("Người chơi X thắng!")
        break

    # Đổi lượt
    current_player = 0 if current_player == 1 else 1


[99, 99, 99]
[99, 99, 99]
[99, 99, 99]

[99, 99, 99]
[99, 1, 99]
[99, 99, 99]

[99, 99, 99]
[99, 1, 99]
[99, 99, 0]

[99, 99, 99]
[1, 1, 99]
[99, 99, 0]

[99, 99, 99]
[1, 1, 99]
[99, 0, 0]

[99, 99, 99]
[1, 1, 1]
[99, 0, 0]

Người chơi X thắng!


BTVN 02
y = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
lấy 4,5,6
lấy 2,5
lấy 3,4
lấy 9,6,3

In [ ]:
import numpy as np
y = [[1,2,3],
     [4,5,6],
     [7,8,9]]
np_list2 = np.array(y)
np_list2


array([2, 5])

In [17]:
#lấy 4,5,6
np_list2[[1],[0,1,2]]

array([4, 5, 6])

In [18]:
#lấy 2,5
np_list2[[0,1],[1]]

array([2, 5])

In [19]:
#lấy 3,4
np_list2[[0,1],[2,0]]

array([3, 4])

In [20]:
#lấy 9,6,3
np_list2[[2,1,0],[2]]

array([9, 6, 3])

BTVN 03
cho x = [1,2,3,4,5,6,7,8,9,10]
1. xuất ra các giá trị chẵn sử dụng if
2. xuất ra các giá trị chẵn sử dụng list comprehension


In [21]:
#Cach 1
x = [1,2,3,4,5,6,7,8,9,10]

for num in x:
    if num % 2 == 0:
        print(num)


2
4
6
8
10


In [22]:
x = [1,2,3,4,5,6,7,8,9,10]

even_numbers = [num for num in x if num % 2 == 0]
print(even_numbers)


[2, 4, 6, 8, 10]


In [57]:
np_x = np.arange(10)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [59]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [60]:
cond1 = np_x % 2 !=0
cond2 = np_x < 5
cond3 = np_x > 0
np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

BTVN 04
tạo 1 mảng numpy có kích thước 150x5. giả sử mảng này chauws 150 mẫu dữ liệu của sv bao gồm chiều cao, cân nặng, tuổi, lương và điểm trung bình. tách mảng dụa trên 4 cột đầu tiên thành 1 biến có tên là X và cột cuối cùng thành y

tách x thành x_train và x_test trong đó x_train chứa 70% dữ liệu và tách y thành y_train và y_test, trong đó chứa 70% dữ liệu
tạo 10 tập dữ liệu x_train không chồng chéo nhau


In [23]:
import numpy as np
# Tạo mảng dữ liệu 150x5 (random để mô phỏng dữ liệu sinh viên)
data = np.random.rand(150, 5)
# X: 4 cột đầu (chiều cao, cân nặng, tuổi, lương)
X = data[:, :4]

# y: cột cuối (điểm trung bình)
y = data[:, 4]
# Số mẫu train (70%)
train_size = int(0.7 * len(X))

# Trộn dữ liệu trước khi chia
indices = np.random.permutation(len(X))

X_shuffled = X[indices]
y_shuffled = y[indices]

# Chia tập train và test
X_train = X_shuffled[:train_size]
X_test = X_shuffled[train_size:]

y_train = y_shuffled[:train_size]
y_test = y_shuffled[train_size:]
# Chia X_train thành 10 tập không chồng chéo
X_train_splits = np.array_split(X_train, 10)
print("Kích thước data:", data.shape)
print("Kích thước X:", X.shape)
print("Kích thước y:", y.shape)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

# Kiểm tra 10 tập X_train
for i, split in enumerate(X_train_splits):
    print(f"Tập X_train {i+1}: {split.shape}")


Kích thước data: (150, 5)
Kích thước X: (150, 4)
Kích thước y: (150,)
X_train: (105, 4)
X_test: (45, 4)
y_train: (105,)
y_test: (45,)
Tập X_train 1: (11, 4)
Tập X_train 2: (11, 4)
Tập X_train 3: (11, 4)
Tập X_train 4: (11, 4)
Tập X_train 5: (11, 4)
Tập X_train 6: (10, 4)
Tập X_train 7: (10, 4)
Tập X_train 8: (10, 4)
Tập X_train 9: (10, 4)
Tập X_train 10: (10, 4)
