In [ ]:
import torch

In [ ]:
torch.cuda

In [8]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv("./iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [10]:
df.shape

(150, 6)

In [15]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
le = LabelEncoder()
X = df.drop(["Species"], axis = 1).values
y = le.fit_transform(df["Species"].values)

#chia du lieu vs test size = 20%
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 42)

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)




In [16]:
len(y_train)

120

In [17]:
label, counts = y_train.unique(return_counts=True)
print(label, counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


In [ ]:
#tinh dao ham bang pytorch
#cho y = 2x^4 + x^3 + 3x^2 + 5x + 1
#tinh y'


In [ ]:
import torch 

In [ ]:
x = torch.tensor(2.0, requires_grad = True)
print(x)
print(x.grad)

In [ ]:
#dinh nghia ham
y= 2*x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)

In [ ]:
y.grad_fn

In [ ]:
#thuc hien lan truyen nguoc va tinh toan cac gradient

y.backward()

In [ ]:
#8x^3 + 3x^2 + 6x + 5

x.grad

btvn 01
cho y = 5x^5 + 6x^3 - 3x + 1
cho biet do doc cua da thuc tren o diem nao

In [ ]:
# BTVN 01
# Tính độ dốc (đạo hàm) của đa thức

import sympy as sp

# Khai báo biến
x = sp.symbols('x')

# Khai báo hàm số
y = 5*x**5 + 6*x**3 - 3*x + 1

# Tính đạo hàm (độ dốc)
dy_dx = sp.diff(y, x)

# In kết quả
print("Hàm số y =", y)
print("Độ dốc (đạo hàm) của hàm là:")
print("y' =", dy_dx)

# Tính độ dốc tại một số điểm minh họa
print("\nĐộ dốc tại x = 0:", dy_dx.subs(x, 0))
print("Độ dốc tại x = 1:", dy_dx.subs(x, 1))
print("Độ dốc tại x = -1:", dy_dx.subs(x, -1))


Hàm số y = 5*x**5 + 6*x**3 - 3*x + 1
Độ dốc (đạo hàm) của hàm là:
y' = 25*x**4 + 18*x**2 - 3

Độ dốc tại x = 0: -3
Độ dốc tại x = 1: 40
Độ dốc tại x = -1: 40


02
tao 1 tensor ban dau co gia tri 2
dinh nghia ham so va tinh gradient
y = x^3 + 2x^2 + 5x + 1
hay tinh dy/dx tai gia tri x
dung pp gradient descent voi lerning rate alpha = 0.1 de cap nhat giatri x trong 10 vong lap

In [19]:
# BTVN 02

import torch

# Khởi tạo tensor x ban đầu
x = torch.tensor(2.0, requires_grad=True)

# Learning rate
alpha = 0.1

print("Giá trị x ban đầu:", x.item())

# Gradient Descent trong 10 vòng lặp
for i in range(10):
    # Định nghĩa hàm số
    y = x**3 + 2*x**2 + 5*x + 1

    # Tính gradient dy/dx
    y.backward()

    # Cập nhật x theo Gradient Descent
    with torch.no_grad():
        x -= alpha * x.grad

    # Reset gradient về 0
    x.grad.zero_()

    print(f"Vòng {i+1}: x = {x.item():.6f}, y = {y.item():.6f}")


Giá trị x ban đầu: 2.0
Vòng 1: x = -0.500000, y = 27.000000
Vòng 2: x = -0.875000, y = -1.125000
Vòng 3: x = -1.254688, y = -2.513672
Vòng 4: x = -1.725085, y = -4.100136
Vòng 5: x = -2.427826, y = -6.807298
Vòng 6: x = -3.724998, y = -13.660884
Vòng 7: x = -6.897680, y = -41.560375
Vòng 8: x = -18.912006, y = -266.510193
Vòng 9: x = -119.146408, y = -6142.375000
Vòng 10: x = -4330.747559, y = -1663589.500000


03
tao 1 tap du lieu gia lap voi x la so gio (ngau nhien tu 1 - 10) va y la so diem dc tinh theo cong thuc y = 3x + 5 + noise
voi noise la gia tri ngau nhien nho

1. khoi tao tham so w va b ngau nhien voi require_grad = true
2. tinh mse
3. tinh gradient
4. cap nhat tham so w va b bang gradient  descent voi lerning rate alpha = 0.01
5. kap lai qua trinh tren trong vong lap de xem su hoi tu cua mo hinh

In [20]:
# BTVN 03 - Giới thiệu về Học sâu

import torch

# 1. Tạo tập dữ liệu giả lập
torch.manual_seed(42)

x = torch.randint(1, 11, (20,), dtype=torch.float32)   # số giờ học
noise = torch.randn(20) * 0.5                          # nhiễu nhỏ
y = 3 * x + 5 + noise                                  # điểm số

# 2. Khởi tạo tham số w, b
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

# Learning rate
alpha = 0.01

# 3. Huấn luyện mô hình
epochs = 100

for epoch in range(epochs):
    # Dự đoán
    y_pred = w * x + b

    # 4. Tính MSE loss
    loss = torch.mean((y_pred - y) ** 2)

    # 5. Tính gradient
    loss.backward()

    # 6. Cập nhật tham số bằng Gradient Descent
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad

    # Reset gradient
    w.grad.zero_()
    b.grad.zero_()

    # In kết quả
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}: Loss = {loss.item():.4f}, w = {w.item():.4f}, b = {b.item():.4f}")


The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.
Epoch 10: Loss = 3.5482, w = 3.6165, b = 1.2903
Epoch 20: Loss = 3.3145, w = 3.5920, b = 1.4407
Epoch 30: Loss = 3.0976, w = 3.5681, b = 1.5856
Epoch 40: Loss = 2.8962, w = 3.5451, b = 1.7253
Epoch 50: Loss = 2.7092, w = 3.5230, b = 1.8598
Epoch 60: Loss = 2.5355, w = 3.5016, b = 1.9895
Epoch 70: Loss = 2.3743, w = 3.4811, b = 2.1144
Epoch 80: Loss = 2.2245, w = 3.4612, b = 2.2348
Epoch 90: Loss = 2.0855, w = 3.4421, b = 2.3508
Epoch 100: Loss = 1.9564, w = 3.4237, b = 2.4626


In [ ]:
import torch
import numpy as np


In [ ]:
torch.__version__

In [24]:
#cuyen doi mang numpy sang tensor pytorch
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))


[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [25]:
x = torch.from_numpy(arr)
print(x)

RuntimeError: Numpy is not available

In [ ]:
print(x.dtype)

In [ ]:
print(x.type())

In [ ]:
arr2 = np.arange(0,12.).reshape(4,3)
arr2

In [ ]:
x2 = torch.from_numpy(arr2)
print(x2)
print (x2.type())

In [22]:
#copy and sharing
x= torch.from_numpy(arr)
print(x)


NameError: name 'arr' is not defined

In [21]:
arr[0] = 99
print(x)



NameError: name 'arr' is not defined

In [ ]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)


In [ ]:
arr[0] = 99
print(x)

04 
giai thich 2 truong hop o tren

04
- Ở trường hợp thứ 1: 
+ torch.from_numpy(arr) không copy dữ liệu
+ Tensor x và mảng numpy arr dùng chung vùng nhớ (shared memory)
+ Khi thay đổi arr[0] = 99 thì x[0] = 99 theo
+ from_numpy sẽ chia sẻ bộ nhớ
+ Thay đổi numpy thì tensor thay đổi
* Đây là lý do sau khi arr[0] = 99 thì print(x) cũng in ra giá trị 99 ở phần tử đầu.

- Ở trường hợp thứ 2:
+ torch.tensor(arr) coppy dữ liệu sang vùng nhớ mới
+ Tensor x độc lập với numpy arr
+ Khi thay đổi arr[0] = 99 thì x[0] không bị ảnh hưởng
+ torch.tensor sẽ copy dữ liệu
+ Thay đổi numpy thì tensor không thay đổi

05
ban giup thay tao tensor voi empyty, zeros, ones, random, reshape voi view as

In [26]:
# BTVN 05 - Giới thiệu về Học sâu
# Tạo tensor: empty, zeros, ones, random, reshape

import torch

# 1. Tạo tensor empty
a = torch.empty(2, 3)
print("Tensor empty:")
print(a)

# 2. Tạo tensor zeros
b = torch.zeros(2, 3)
print("\nTensor zeros:")
print(b)

# 3. Tạo tensor ones
c = torch.ones(2, 3)
print("\nTensor ones:")
print(c)

# 4. Tạo tensor random
d = torch.rand(2, 3)
print("\nTensor random:")
print(d)

# 5. Reshape bằng view
e = torch.arange(0, 6)
print("\nTensor ban đầu:")
print(e)

e_view = e.view(2, 3)
print("\nReshape bằng view (2x3):")
print(e_view)

# 6. Reshape bằng as (reshape)
e_as = e.reshape(3, 2)
print("\nReshape bằng reshape (3x2):")
print(e_as)


Tensor empty:
tensor([[-6.0878e+20,  1.8833e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

Tensor zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])

Tensor ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Tensor random:
tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])

Tensor ban đầu:
tensor([0, 1, 2, 3, 4, 5])

Reshape bằng view (2x3):
tensor([[0, 1, 2],
        [3, 4, 5]])

Reshape bằng reshape (3x2):
tensor([[0, 1],
        [2, 3],
        [4, 5]])
